services:
  flask-api:
    build: .
    image: flask-api-image
    container_name: flask-api
    restart: unless-stopped

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      # Auto-découverte Prometheus
      - prometheus.io/scrape=true
      - prometheus.io/port=5000
      - prometheus.io/path=/metrics
      # Domaine de l'API
      - traefik.http.routers.flask-api.rule=Host(`flask-api.devitlab.ddns.net`)
      - traefik.http.routers.flask-api.entrypoints=websecure
      - traefik.http.routers.flask-api.tls.certresolver=letsencrypt
      # Port interne du conteneur Flask
      - traefik.http.services.flask-api.loadbalancer.server.port=5000

    networks:
      - traefik-net
      - monitoring   # pour que Prometheus puisse scraper /metrics

networks:
  traefik-net:
    external: true
  # Réseau de la stack observability (préfixé par le nom du dossier)
  monitoring:
    external: true
    name: observability_monitoring
