{
 "title": "Flask API",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requêtes / seconde",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(hello_requests_total[1m])", "legendFormat": "req/s - status {{status}}" }
   ]
  },
  {
   "title": "Total requêtes",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(hello_requests_total)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Statut HTTP",
   "type": "piechart",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 8 },
   "targets": [
    {
     "expr": "sum by (status) (hello_requests_total)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "API up/down",
   "type": "stat",
   "gridPos": { "x": 12, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "up{job=\"flask-api\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "Latence moyenne (ms)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[1m]) / rate(flask_http_request_duration_seconds_count[1m]) * 1000",
     "legendFormat": "latence moy. (ms)"
    }
   ]
  },
  {
   "title": "Erreurs 5xx / seconde",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{status=~\"5..\"}[1m])",
     "legendFormat": "erreurs 5xx"
    }
   ]
  }
 ]
}